networkFile: network
pathsFile: paths
gap: 0
weights: [0.5, 0.5]
serverCapacity: 1000
serversPerNode: 1
linkCapacity: 1000
maxReplicas: 3
functionTypes:
  0:
    type: 0
    replicable: false
    load: 1.0
  1:
    type: 1
    replicable: true
    load: 1.0
  2:
    type: 2
    replicable: false
    load: 1.0
serviceTypes:
  0:
    id: 0
    chain: [0, 1, 2]
trafficFlows:
  - src: "n1"
    dst: "n9"
    serviceId: 0
  - src: "n2"
    dst: "n9"
    serviceId: 0
minDemands: 3
maxDemands: 3
minBw: 100
maxBw: 100
auxValues: [1000, 10]