networkFile: network.dgs
bidirectionalLinks: true
minReplicas: 0
maxReplicas: 3
gap: 0
alpha: 0
beta: 1
serverCapacity: 1000
serversPerNode: 2

services:
  - id: 0
    functions:
    - id: 0
      replicable: false
      load: 0.2
    - id: 1
      replicable: true
      load: 1.0
    - id: 2
      replicable: false
      load: 0.2

trafficFlows:
  - src: "A"
    dst: "D"
    serviceId: 0
minDemands: 3
maxDemands: 3
minBw: 200
maxBw: 200